[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ferrisil-csc245-portfolio"
authors = [{name = "Leonardo Ferrisi", email = "ferrisil@union.edu"}]
dynamic = ["version", "description"]
